In [1]:
import pandas as pd

s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [2]:
data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)
print(df)

  Name  Age  Marks
0    A   20     85
1    B   21     90
2    C   22     88

In [4]:
df = pd.DataFrame(
    [[1,2],[3,4]],
    index=["Row1","Row2"],
    columns=["Col1","Col2"]
)

In [6]:
df = pd.read_csv("student.csv.csv")

In [7]:
df.head()

,student_id,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
0,1,Male,53,79,56,8.87,50,92,90,1,3,23,4,91,4,Yes,0,0.00
1,2,Female,56,54,59,6.78,61,51,99,1,0,6,5,87,3,No,0,0.00
2,3,Male,94,83,83,7.92,91,93,84,1,1,10,2,81,2,No,1,6.92
3,4,Male,84,71,87,6.57,85,60,72,4,2,14,5,87,3,No,0,0.00
4,5,Male,58,88,74,9.01,73,52,88,1,2,20,0,60,1,No,0,0.00

In [8]:
df.tail()

,student_id,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
4995,4996,Male,68,50,67,8.32,51,57,96,1,1,15,1,71,4,Yes,0,0.0
4996,4997,Female,61,52,56,9.47,61,59,62,3,4,0,3,73,5,Yes,0,0.0
4997,4998,Male,74,76,58,6.19,40,99,89,1,1,2,2,67,1,No,0,0.0
4998,4999,Female,84,67,66,8.07,40,48,92,4,1,6,4,61,0,No,0,0.0
4999,5000,Female,61,79,64,6.97,42,80,59,4,5,2,5,93,4,Yes,0,0.0

In [9]:
df.shape

(5000, 18)

In [10]:
df.columns

Index(['student_id', 'gender', 'ssc_percentage', 'hsc_percentage',
       'degree_percentage', 'cgpa', 'entrance_exam_score',
       'technical_skill_score', 'soft_skill_score', 'internship_count',
       'live_projects', 'work_experience_months', 'certifications',
       'attendance_percentage', 'backlogs', 'extracurricular_activities',
       'placement_status', 'salary_package_lpa'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  5000 non-null   int64
 1   gender                      5000 non-null   object
 2   ssc_percentage              5000 non-null   int64
 3   hsc_percentage              5000 non-null   int64
 4   degree_percentage           5000 non-null   int64
 5   cgpa                        5000 non-null   float64
 6   entrance_exam_score         5000 non-null   int64
 7   technical_skill_score       5000 non-null   int64
 8   soft_skill_score            5000 non-null   int64
 9   internship_count            5000 non-null   int64
 10  live_projects               5000 non-null   int64
 11  work_experience_months      5000 non-null   int64
 12  certifications              5000 non-null   int64
 13  attendance_percentage       5000 non-null   int64
 14  backlogs                    5000 non-null   int64
 15  extracurricular_activities  5000 non-null   object
 16  placement_status            5000 non-null   int64
 17  salary_package_lpa          5000 non-null   float64
dtypes: float64(2), int64(14), object(2)
memory usage: 703.3+ KB

In [12]:
df.describe()

,student_id,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,placement_status,salary_package_lpa
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000
mean,2500.500000,72.425800,71.910800,71.845200,7.678326,69.197800,69.651000,69.839600,1.987800,2.491800,11.982000,2.481000,79.433400,2.518400,0.173200,1.59589
std,1443.520003,13.199642,12.842781,10.013196,1.237084,17.325528,17.179704,17.170732,1.410975,1.704967,7.258114,1.719485,11.638585,1.721004,0.378458,3.77582
min,1.000000,50.000000,50.000000,55.000000,5.500000,40.000000,40.000000,40.000000,0.000000,0.000000,0.000000,0.000000,60.000000,0.000000,0.000000,0.00000
25%,1250.750000,61.000000,61.000000,63.000000,6.617500,54.000000,55.000000,55.000000,1.000000,1.000000,6.000000,1.000000,69.000000,1.000000,0.000000,0.00000
50%,2500.500000,72.000000,72.000000,72.000000,7.700000,69.000000,70.000000,69.000000,2.000000,3.000000,12.000000,2.000000,80.000000,3.000000,0.000000,0.00000
75%,3750.250000,84.000000,83.000000,80.000000,8.750000,84.000000,84.000000,85.000000,3.000000,4.000000,18.000000,4.000000,89.000000,4.000000,0.000000,0.00000
max,5000.000000,95.000000,94.000000,89.000000,9.800000,99.000000,99.000000,99.000000,4.000000,5.000000,24.000000,5.000000,99.000000,5.000000,1.000000,14.99000

In [14]:
df["student_id"]

0          1
1          2
2          3
3          4
4          5
        ...
4995    4996
4996    4997
4997    4998
4998    4999
4999    5000
Name: student_id, Length: 5000, dtype: int64

In [15]:
df[["student_id","cgpa"]]

      student_id  cgpa
0              1  8.87
1              2  6.78
2              3  7.92
3              4  6.57
4              5  9.01
...          ...   ...
4995        4996  8.32
4996        4997  9.47
4997        4998  6.19
4998        4999  8.07
4999        5000  6.97

[5000 rows x 2 columns]

In [16]:
df.loc[0:2]

,student_id,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
0,1,Male,53,79,56,8.87,50,92,90,1,3,23,4,91,4,Yes,0,0.00
1,2,Female,56,54,59,6.78,61,51,99,1,0,6,5,87,3,No,0,0.00
2,3,Male,94,83,83,7.92,91,93,84,1,1,10,2,81,2,No,1,6.92

In [17]:
df.iloc[0:2]

,student_id,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
0,1,Male,53,79,56,8.87,50,92,90,1,3,23,4,91,4,Yes,0,0.0
1,2,Female,56,54,59,6.78,61,51,99,1,0,6,5,87,3,No,0,0.0

In [20]:
df[df["ssc_percentage"] > 85]

,student_id,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
2,3,Male,94,83,83,7.92,91,93,84,1,1,10,2,81,2,No,1,6.92
6,7,Male,94,52,59,9.07,85,92,43,2,0,6,1,70,5,Yes,0,0.00
13,14,Male,87,57,75,5.77,78,64,45,3,0,0,4,86,0,Yes,0,0.00
17,18,Female,95,61,87,7.10,66,65,78,0,5,4,4,66,2,Yes,1,6.76
24,25,Female,92,73,56,8.32,92,64,45,0,4,2,1,93,5,No,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4974,4975,Female,88,58,73,5.93,60,55,85,2,1,2,2,79,4,Yes,0,0.00
4975,4976,Female,86,63,84,9.17,92,77,82,1,3,22,1,60,2,No,1,10.93
4978,4979,Female,94,52,67,6.43,82,91,50,0,4,23,5,63,2,Yes,0,0.00
4982,4983,Male,87,81,59,5.96,40,60,84,2,0,18,5,99,0,Yes,0,0.00
4989,4990,Female,90,71,62,6.46,40,53,71,4,0,13,1,96,1,No,0,0.00

In [21]:
df[df["ssc_percentage"] > df["ssc_percentage"].mean()]

,student_id,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
2,3,Male,94,83,83,7.92,91,93,84,1,1,10,2,81,2,No,1,6.92
3,4,Male,84,71,87,6.57,85,60,72,4,2,14,5,87,3,No,0,0.00
6,7,Male,94,52,59,9.07,85,92,43,2,0,6,1,70,5,Yes,0,0.00
9,10,Female,82,54,74,7.83,78,99,99,2,3,19,2,72,4,No,0,0.00
10,11,Male,81,73,62,6.71,75,99,55,1,1,19,5,80,5,No,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,4988,Male,75,54,66,8.94,79,65,85,1,2,18,5,74,0,Yes,1,10.96
4989,4990,Female,90,71,62,6.46,40,53,71,4,0,13,1,96,1,No,0,0.00
4991,4992,Male,82,91,63,6.64,83,79,78,3,1,11,4,81,5,No,0,0.00
4997,4998,Male,74,76,58,6.19,40,99,89,1,1,2,2,67,1,No,0,0.00
4998,4999,Female,84,67,66,8.07,40,48,92,4,1,6,4,61,0,No,0,0.00

In [23]:
df.loc[0,"ssc_percentage"]

np.int64(53)

In [24]:
df.set_index("student_id", inplace=True)

In [25]:
df.reset_index(inplace=True)

In [26]:
df.rename(columns={"student_id":"cgpa"}, inplace=True)

Data Cleaning & Manipulation

In [27]:
df.isnull()

,cgpa,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
df["cgpa"].fillna(df["cgpa"].mean(), inplace=True)

/tmp/ipykernel_9504/105179394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["cgpa"].fillna(df["cgpa"].mean(), inplace=True)

In [32]:
df.dropna(inplace=True)

In [37]:
df["hsc_percentage"] = df["hsc_percentage"].apply(lambda x: 0 if x < 0 else x)

In [38]:
df.drop_duplicates(inplace=True)

In [41]:
df.sort_values("hsc_percentage", ascending=False)

,cgpa,gender,ssc_percentage,hsc_percentage,degree_percentage,cgpa,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,extracurricular_activities,placement_status,salary_package_lpa
2310,2311,Female,55,94,75,7.92,66,97,89,1,3,14,3,82,3,No,0,0.00
4968,4969,Male,51,94,72,6.96,64,94,44,1,3,6,0,74,4,No,0,0.00
2320,2321,Male,64,94,68,7.74,77,43,99,4,5,0,0,72,4,Yes,0,0.00
19,20,Male,65,94,80,7.03,70,77,81,3,5,1,5,74,2,No,1,9.42
1743,1744,Male,59,94,74,8.83,41,75,89,1,0,6,5,97,3,Yes,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,476,Female,77,50,74,6.44,89,77,56,2,3,21,1,81,3,No,0,0.00
4936,4937,Male,77,50,63,8.55,63,81,77,1,0,9,4,82,4,No,0,0.00
2341,2342,Male,72,50,80,9.53,47,98,81,4,4,10,5,80,4,No,0,0.00
2253,2254,Female,51,50,75,8.01,86,52,70,2,2,18,4,79,0,Yes,0,0.00
2261,2262,Female,51,50,76,7.18,89,80,46,4,0,16,4,64,3,Yes,0,0.00

In [43]:
df["hsc_percentage"] = df["hsc_percentage"].apply(lambda x: x + 5)

In [47]:
df["total"] = df["ssc_percentage"] + df["hsc_percentage"]

In [48]:
df["cgpa"] = df["cgpa"].astype(float)

In [50]:
df.drop("cgpa", axis=1, inplace=True)

Statistical Operations

In [52]:
df["ssc_percentage"].mean()

np.float64(72.4258)

In [53]:
df["ssc_percentage"].median()
df["ssc_percentage"].std()

np.float64(13.199641679534093)

In [54]:
df["ssc_percentage"].max()
df["ssc_percentage"].min()

np.int64(50)

In [56]:
df.corr(numeric_only=True)

,ssc_percentage,hsc_percentage,degree_percentage,entrance_exam_score,technical_skill_score,soft_skill_score,internship_count,live_projects,work_experience_months,certifications,attendance_percentage,backlogs,placement_status,salary_package_lpa,total
ssc_percentage,1.000000,-0.019349,0.009593,-0.016133,-0.017894,-0.012745,-0.022824,0.008257,0.009549,-0.021682,-0.013790,0.006008,-0.000030,-0.002207,0.710137
hsc_percentage,-0.019349,1.000000,-0.012460,-0.010286,0.004797,-0.002642,-0.012104,-0.019474,-0.014230,-0.024707,-0.001179,0.001939,0.017378,0.012632,0.690191
degree_percentage,0.009593,-0.012460,1.000000,-0.004231,0.000409,0.013315,0.028425,0.012123,0.014027,0.028933,-0.019107,0.009847,-0.012085,-0.009829,-0.001831
entrance_exam_score,-0.016133,-0.010286,-0.004231,1.000000,0.010851,0.008591,-0.028517,-0.002176,0.000362,0.002547,0.007207,-0.007176,0.000937,-0.001009,-0.018920
technical_skill_score,-0.017894,0.004797,0.000409,0.010851,1.000000,0.004897,0.019498,-0.007163,0.008767,-0.010880,0.016092,0.031844,0.246573,0.223200,-0.009573
soft_skill_score,-0.012745,-0.002642,0.013315,0.008591,0.004897,1.000000,-0.002855,-0.018105,0.004155,0.008650,0.013930,-0.000658,0.197685,0.182165,-0.011085
internship_count,-0.022824,-0.012104,0.028425,-0.028517,0.019498,-0.002855,1.000000,0.002661,0.005741,0.023527,-0.013029,-0.014447,0.011075,0.003564,-0.025043
live_projects,0.008257,-0.019474,0.012123,-0.002176,-0.007163,-0.018105,0.002661,1.000000,-0.021916,-0.032601,-0.014494,0.008607,-0.001519,-0.003859,-0.007737
work_experience_months,0.009549,-0.014230,0.014027,0.000362,0.008767,0.004155,0.005741,-0.021916,1.000000,-0.006904,-0.006567,-0.008845,0.021453,0.013853,-0.003110
certifications,-0.021682,-0.024707,0.028933,0.002547,-0.010880,0.008650,0.023527,-0.032601,-0.006904,1.000000,0.019698,-0.010461,0.007517,-0.003365,-0.033091
attendance_percentage,-0.013790,-0.001179,-0.019107,0.007207,0.016092,0.013930,-0.013029,-0.014494,-0.006567,0.019698,1.000000,0.002763,-0.012050,-0.014698,-0.010811
backlogs,0.006008,0.001939,0.009847,-0.007176,0.031844,-0.000658,-0.014447,0.008607,-0.008845,-0.010461,0.002763,1.000000,-0.401394,-0.376909,0.005714
placement_status,-0.000030,0.017378,-0.012085,0.000937,0.246573,0.197685,0.011075,-0.001519,0.021453,0.007517,-0.012050,-0.401394,1.000000,0.923552,0.012216
salary_package_lpa,-0.002207,0.012632,-0.009829,-0.001009,0.223200,0.182165,0.003564,-0.003859,0.013853,-0.003365,-0.014698,-0.376909,0.923552,1.000000,0.007298
total,0.710137,0.690191,-0.001831,-0.018920,-0.009573,-0.011085,-0.025043,-0.007737,-0.003110,-0.033091,-0.010811,0.005714,0.012216,0.007298,1.000000

In [60]:
df["student_id"].nunique()

KeyError: 'student_id'

In [63]:
df["hsc_percentage"].cumsum()

0           84
1          143
2          231
3          307
4          400
         ...
4995    384260
4996    384317
4997    384398
4998    384470
4999    384554
Name: hsc_percentage, Length: 5000, dtype: int64

In [64]:
df["hsc_percentage"].value_counts()

hsc_percentage
67    136
70    134
87    129
71    129
83    124
73    122
80    122
78    120
96    119
77    119
98    119
91    119
64    119
85    118
97    117
76    115
82    115
61    115
63    114
66    113
79    112
72    111
62    111
57    111
69    110
60    110
93    110
58    107
68    107
55    105
81    104
90    104
75    103
95    102
59    101
99    101
92    100
65    100
86     99
74     97
88     96
56     96
84     95
94     95
89     95
Name: count, dtype: int64

In [67]:
df["hsc_percentage"] = (df["hsc_percentage"] - df["hsc_percentage"].min()) / (df["hsc_percentage"].max() - df["hsc_percentage"].min())

In [70]:
df.groupby("ssc_percentage")["hsc_percentage"].mean()

ssc_percentage
50    0.524492
51    0.472925
52    0.524161
53    0.518669
54    0.540357
55    0.526879
56    0.474376
57    0.518825
58    0.470365
59    0.531385
60    0.486591
61    0.527846
62    0.502505
63    0.527365
64    0.512378
65    0.557296
66    0.477814
67    0.499061
68    0.501446
69    0.470749
70    0.516143
71    0.490991
72    0.439986
73    0.415617
74    0.474958
75    0.500176
76    0.490431
77    0.435573
78    0.521562
79    0.485517
80    0.502109
81    0.505138
82    0.515152
83    0.474242
84    0.488105
85    0.527230
86    0.512626
87    0.509252
88    0.474936
89    0.449333
90    0.511127
91    0.522912
92    0.496470
93    0.495455
94    0.489636
95    0.505502
Name: hsc_percentage, dtype: float64

In [80]:
pd.pivot_table(df, values="cgpa", index="student_id", aggfunc="cgpa")

KeyError: 'cgpa'

Part B – Advanced Pandas

In [81]:
df["Norm"] = df.groupby("ssc_percentage")["hsc_percentage"].transform(
    lambda x: (x - x.mean()) / x.std()
)

In [82]:
df["ssc_percentage"] = df["hsc_percentage"].rolling(3).mean()

In [84]:
mean = df["ssc_percentage"].mean()
std = df["ssc_percentage"].std()

outliers = df[(df["ssc_percentage"] > mean + 3*std) | (df["ssc_percentage"] < mean - 3*std)]

In [106]:
import pandas as pd

df1 = pd.DataFrame({
    "Student ID": [1,2,3],
    "Name": ["A","B","C"]
})

df2 = pd.DataFrame({
    "ID": [1,2,4],
    "CGPA": [85,90,95]
})

In [107]:
pd.concat([df1, df2])

   Student ID Name   ID  CGPA
0         1.0    A  NaN   NaN
1         2.0    B  NaN   NaN
2         3.0    C  NaN   NaN
0         NaN  NaN  1.0  85.0
1         NaN  NaN  2.0  90.0
2         NaN  NaN  4.0  95.0

In [108]:
df["hsc_percentage"] = df["hsc_percentage"].apply(lambda x: "Pass" if x>=40 else "Fail")

KeyError: 'hsc_percentage'

In [93]:
df["hsc_percentage"] = df.groupby("hsc_percentage")["ssc_percentage"].rank()

In [94]:
df["hsc_percentage"] = df["hsc_percentage"].apply(lambda x: x*2)

In [101]:
df["ssc_percentage"] = pd.to_datetime(df["ssc_percentage"])
df.set_index("ssc_percentage", inplace=True)

df.resample("cgpa").mean()

KeyError: 'ssc_percentage'

In [112]:
df[df.duplicated(["student_id","ssc_percentage"])]

KeyError: Index(['student_id', 'ssc_percentage'], dtype='object')